name: jfrgo-cli-docker-push

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JFrog-CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
      - run: jf --version
