name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Build Docker image
        run: |
          jf docker build -t ${{ secrets.JF_BASE_URL }}/yoavh-docker-local/github-test . 
      - name: Push Docker image
        run: |
          jf docker push ${{ secrets.JF_BASE_URL }}/yoavh-docker-local/github-test
      - name: NPM config
        run: jf npmc --repo-resolve yoavh-npm --repo-deploy yoavh-npm
      - name: NPM install
        run: jf npm ci
      - name: NPM publish
        run: jf npm publish
      - name: Publish build-info
        run: jf rt bp
        
