name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Basic authentication credentials
          ## JF_USER: ${{ secrets.JF_USER }}
          ## JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JF_BASE_URL }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          jf docker build -t ${{ secrets.JF_BASE_URL }}/yoavh-docker-local/github-test .
          jf docker push ${{ secrets.JF_BASE_URL }}/yoavh-docker-local/github-test
